---
title: "Final Project - First Visualization"
output:
  pdf_document: default
author: "Group 10"
date: "2025-11-03"
---

# Question statement: 
  What is the most popular payment method among customers in the United Kingdom (UK) and the United States (USA) based on recent e-commerce transaction data?


# Library Setup
```{r}
library(tidyverse)
library(stringr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(tidytext)
```

# Data Importing
```{r tidy=TRUE}
ecommerce <- read.csv('ecommerce_dataset_10000.csv')

head(ecommerce)
```

# Data Cleaning
```{r}
ecommerce <- ecommerce %>%
  mutate(
    order_year = year(ymd(order_date))
  )
summary(ecommerce$order_year)
```

```{r tidy=TRUE}
ecommerce_clean <- ecommerce %>%
  filter(
    !is.na(payment_method),
    country %in% c("UK", "USA"),
    order_year %in% c(2022, 2024)
  )

head(ecommerce_clean)
```

# Calculate Most Popular Payment Method by Country
## UK Most Popular Payment Method
```{r tidy=TRUE}
payment_summary_uk <- ecommerce_clean %>%
  filter(country == "UK", order_year %in% c(2022, 2024)) %>%
  group_by(order_year, payment_method) %>%
  summarise(total_transactions = n(), .groups = "drop")

payment_summary_uk

top_methods_uk <- payment_summary_uk %>%
  group_by(payment_method) %>%
  summarise(overall = sum(total_transactions)) %>%
  slice_max(overall, n = 3) %>%
  pull(payment_method)

top_methods_uk
```

## USA Most Popular Payment Method
```{r tidy=TRUE}
payment_summary_usa <- ecommerce_clean %>%
  filter(country == "USA", order_year %in% c(2022, 2024)) %>%
  group_by(order_year, payment_method) %>%
  summarise(total_transactions = n(), .groups = "drop")

payment_summary_usa

top_methods_usa <- payment_summary_usa %>%
  group_by(payment_method) %>%
  summarise(overall = sum(total_transactions)) %>%
  slice_max(overall, n = 3) %>%
  pull(payment_method)

top_methods_usa
```